# Main Script Settings
main:
  run_dir: ./ex_mu  # directory to save the trained model
  load: False       # whether to load a trained model

# Tokenizer Settings
model_config:

  # Meta data
  name: mu_transform_tokenizer

  # Model config
  n_tokens: 256
  mu: 255
  normalization: max_abs
